In [1]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('/content/customer.csv')

In [4]:
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [5]:
df.sample(5)

    age  gender   review education purchased
2    70  Female     Good        PG        No
36   34  Female     Good        UG       Yes
4    16  Female  Average        UG        No
33   89  Female     Good        PG       Yes
11   74    Male     Good        UG       Yes

In [6]:
df = df.iloc[:,2:]

In [7]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size=0.2)

In [27]:
from re import X
X_train

     review education
9      Good        UG
48     Good        UG
25     Good    School
46     Poor        PG
39     Poor        PG
40     Good    School
37  Average        PG
19     Poor        PG
11     Good        UG
36     Good        UG
18     Good    School
27     Poor        PG
26     Poor        PG
34  Average    School
30  Average        UG
47     Good        PG
5   Average    School
45     Poor        PG
22     Poor        PG
42     Good        PG
7      Poor    School
24  Average        PG
0   Average    School
2      Good        PG
32  Average        UG
8   Average        UG
6      Good    School
33     Good        PG
16     Poor        UG
38     Good    School
17     Poor        UG
3      Good        PG
10     Good        UG
15     Poor        UG
21  Average        PG
4   Average        UG
20  Average    School
35     Poor    School
13  Average    School
41     Good        PG

In [28]:
from sklearn.preprocessing import OrdinalEncoder

In [29]:
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [30]:
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)

In [31]:
X_train

array([[2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [2., 2.]])

In [32]:
X_test

array([[0., 2.],
       [2., 0.],
       [0., 0.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [0., 1.],
       [2., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [36]:
X_train

array([[2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [2., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 0.],
       [1., 2.],
       [1., 0.],
       [2., 2.],
       [1., 1.],
       [1., 1.],
       [2., 0.],
       [2., 2.],
       [0., 1.],
       [2., 0.],
       [0., 1.],
       [2., 2.],
       [2., 1.],
       [0., 1.],
       [1., 2.],
       [1., 1.],
       [1., 0.],
       [0., 0.],
       [1., 0.],
       [2., 2.]])

In [37]:
from sklearn.preprocessing import LabelEncoder

In [38]:
le = LabelEncoder()

In [44]:
le.fit(Y_train)

LabelEncoder()

In [45]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [46]:
Y_train = le.transform(Y_train)
Y_test = le.transform(Y_test)

In [47]:
Y_train

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1])